"""New Migration

Revision ID: c16c39df153e
Revises: 
Create Date: 2024-04-16 12:00:26.567148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16c39df153e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protein', sa.String(), nullable=True),
    sa.Column('tortilla', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taco_id'), 'taco', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taco_id'), table_name='taco')
    op.drop_table('taco')
    # ### end Alembic commands ###
