name: fast_tacos
services:
  taco_db:
    image: postgres:10
    container_name: taco_db
    env_file:
      - ../.env
    ports:
      - "5432:5432"
  taco_web:
    container_name: taco_web
    build:
      context: ../
      dockerfile: setup/Dockerfile
    ports: 
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - taco_db